### ISSUE TITLE
Migrate to SPM

### ISSUE THREAD

**Issue by henrik-dmg** [vincent-pradeilles/KeyPathTesting#1]
Given the rising popularity of SPM, it would make sense to migrate this project to be a Swift package. CocoaPods will still work if the `s.source_files` path is updated. Not sure about Carthage though, since you'd have to link XCTest.

If you don't really plan on adding more features to this project though, I think it might be worth considering dropping Carthage support (users who really really still want to use Carthage can do so by specifying `0.1.4` as the version though) in favour of all the benefits SPM brings

**Comment by henrik-dmg** [comment]
If you're interested, I have a fork of this repo where I migrated to SPM and would be happy to submit a PR. I could not get Carthage to work though

**Comment by vincent-pradeilles** [comment]
Totally agree, not supporting SPM is due to a lack of time. If you feel like doing a PR, you're more than welcome!
